#include "Easy_Menu_User.h"

/* Easy Menu User Configuration File */
/* This file is auto-generated by Easy Menu Builder */
/* Configuration: 测试文件 */

/* USER CODE PUBLIC BEGIN */
#include "ti_msp_dl_config.h"
#include "oled.h"
#include "OLED_Data.h"
#include "control.h"
/* USER CODE PUBLIC END */

/* ================================================================= 占位变量 ================================================================= */
struct {
    unsigned char LED1__data;
    unsigned char LED2__data;
    unsigned char LED3__data;
    unsigned char LED4__data;
    unsigned char uint8_data;
    unsigned short int uint16_data;
    unsigned int uint32_data;
    signed char int8_data;
    signed short int int16_data;
    signed int int32_data;
    float float_data;
    unsigned char hours;
    unsigned char minutes;
    unsigned char seconds;
    unsigned char millisecond;
} Easy_Menu_Ui_Data = {
    .LED1__data = 0,
    .LED2__data = 0,
    .LED3__data = 0,
    .LED4__data = 0,
    .uint8_data = 1,
    .uint16_data = 2,
    .uint32_data = 3,
    .int8_data = 4,
    .int16_data = 5,
    .int32_data = 6,
    .float_data = 7.0f,
    .hours = 23,
    .minutes = 59,
    .seconds = 55,
    .millisecond = 0,
};
/* ============================================================== 页面、条目定义 ============================================================== */    
Ordinary_Page main_page;
    Goto_Item goto__start_page;
    Goto_Item goto__Switch_Page;
    Goto_Item goto__Data_Page;
    Goto_Item goto__User_Show_Page;
    Show_Page start_page;
    Ordinary_Page Switch_Page;
        Switch_Item switch_page__1__item;
        Switch_Item switch_page__2__item;
        Switch_Item switch_page__3__item;
        Switch_Item switch_page__4__item;
    Ordinary_Page Data_Page;
        Data_Item data_page__1__item;
        Data_Item data_page__2__item;
        Data_Item data_page__3__item;
        Data_Item data_page__4__item;
        Data_Item data_page__5__item;
        Data_Item data_page__6__item;
        Data_Item data_page__7__item;
    Ordinary_Page User_Show_Page;
        Show_Item user_show_page__1__item;
        Show_Item user_show_page__2__item;
        Show_Item user_show_page__3__item;
        Show_Item user_show_page__4__item;
/* ============================================================== 回调函数（条目） ============================================================ */
void Switch_Page__1__Item_Callback(unsigned char data)
{
    /* USER CODE BEGIN */
    if (data) {
        DL_GPIO_setPins(LED_PORT, LED_B14_PIN);
    } else {
        DL_GPIO_clearPins(LED_PORT, LED_B14_PIN);
    }
    /* USER CODE END */
}

void Switch_Page__2__Item_Callback(unsigned char data)
{
    /* USER CODE BEGIN */
    if (data) {
        DL_GPIO_setPins(LED_A_PORT, LED_A28_PIN);
    } else {
        DL_GPIO_clearPins(LED_A_PORT, LED_A28_PIN);
    }
    /* USER CODE END */
}

void Switch_Page__3__Item_Callback(unsigned char data)
{
    /* USER CODE BEGIN */
    if (data) {
        DL_GPIO_setPins(LED_A_PORT, LED_A29_PIN);
    } else {
        DL_GPIO_clearPins(LED_A_PORT, LED_A29_PIN);
    }
    /* USER CODE END */
}

void Switch_Page__4__Item_Callback(unsigned char data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Data_Page__1__Item_Callback(void *data) // *((unsigned char*)data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Data_Page__2__Item_Callback(void *data) // *((unsigned short int*)data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Data_Page__3__Item_Callback(void *data) // *((unsigned int*)data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Data_Page__4__Item_Callback(void *data) // *((signed char*)data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Data_Page__5__Item_Callback(void *data) // *((signed short int*)data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Data_Page__6__Item_Callback(void *data) // *((signed int*)data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void Data_Page__7__Item_Callback(void *data) // *((float*)data)
{
    /* USER CODE BEGIN */

    /* USER CODE END */
}

void User_Show_Page__1__Item_Callback(void)
{
    /* USER CODE BEGIN */
    if(Easy_Menu_Ui_Data.hours >= 24)
    {
        Easy_Menu_Ui_Data.hours = 0;
    }
    /* USER CODE END */
}

void User_Show_Page__2__Item_Callback(void)
{
    /* USER CODE BEGIN */
    if(Easy_Menu_Ui_Data.minutes >= 60) 
    {
        Easy_Menu_Ui_Data.minutes = 0;
        Easy_Menu_Ui_Data.hours++;
    }
    /* USER CODE END */
}

void User_Show_Page__3__Item_Callback(void)
{
    /* USER CODE BEGIN */
    if(Easy_Menu_Ui_Data.seconds >= 60) 
    {
        Easy_Menu_Ui_Data.seconds = 0;
        Easy_Menu_Ui_Data.minutes++;
    }
    /* USER CODE END */
}

void User_Show_Page__4__Item_Callback(void)
{
    /* USER CODE BEGIN */
    static unsigned int Show_Page_4_Item_Last_Tick = 0;
    
    Easy_Menu_Ui_Data.millisecond += (easy_menu.tick - Show_Page_4_Item_Last_Tick) / 10;

    Show_Page_4_Item_Last_Tick = easy_menu.tick;
    
    if(Easy_Menu_Ui_Data.millisecond >= 100) 
    {
        Easy_Menu_Ui_Data.millisecond = 0;
        Easy_Menu_Ui_Data.seconds++;
    }
    /* USER CODE END */
}

/* ============================================================== 回调函数（页面） ============================================================ */
/* Private variables ---------------------------------------------------------*/
/* USER CODE VALUE BEGIN */
const char ch[4] = {'|', '/', '-', '\\'};
unsigned char show_page_len = 0;
unsigned char show_page_index = 0;
unsigned char ch_index = 0;
static uint8_t start_page_cat_frame = 0;
static int16_t start_page_cat_x_offset = -128;
/* USER CODE VALUE END */
/* Private function ----------------------------------------------------------*/
void Start_Page_Enter_Callback(void)
{
    /* USER CODE BEGIN */
    // 进入 Start 页面就启动循迹控制；控制任务会按 20ms 周期真正读取灰度并驱动 TB6612。
    // 小猫动画也从屏幕左侧重新开始，保留 Start 页面的“灵魂”。
    start_page_cat_frame = 0;
    start_page_cat_x_offset = -128;
    oled_clear();
    Control_StartLineFollow();
    /* USER CODE END */
}

void Start_Page_Period_Callback(void* temp, Easy_Menu_Input_TYPE user_input)
{
    /* USER CODE BEGIN */
    (void)temp;

    // Start 页面作为运行页：任意按键都立即停车并回到主菜单，避免小车失控。
    if (user_input != EASY_MENU_NONE) {
        Control_Stop();
        Easy_Menu_Goto_Page(PAGE(main_page));
        return;
    }

    // 循迹在控制任务里后台运行；这里继续画小猫，让跑车和动画同时存在。
    oled_draw_cat_frame(YueXinMao[start_page_cat_frame], start_page_cat_x_offset);

    // 每次跳过一帧，让猫咪本身的动作加快两倍。
    start_page_cat_frame += 2;
    if (start_page_cat_frame >= 22) {
        start_page_cat_frame = 0;
    }

    // 小猫保持原来的横向移动速度，从左到右循环穿屏。
    start_page_cat_x_offset += 2;
    if (start_page_cat_x_offset > 128) {
        start_page_cat_x_offset = -128;
    }
    /* USER CODE END */
}

/* =========================================================== 设置列表（普通页面） =========================================================== */
Item *main_page_items[4] = {
    ITEM(goto__start_page),
    ITEM(goto__Switch_Page),
    ITEM(goto__Data_Page),
    ITEM(goto__User_Show_Page)
};

Item *Switch_Page_items[3] = {
    ITEM(switch_page__1__item),
    ITEM(switch_page__2__item),
    ITEM(switch_page__3__item)
};

Item *Data_Page_items[7] = {
    ITEM(data_page__1__item),
    ITEM(data_page__2__item),
    ITEM(data_page__3__item),
    ITEM(data_page__4__item),
    ITEM(data_page__5__item),
    ITEM(data_page__6__item),
    ITEM(data_page__7__item)
};

Item *User_Show_Page_items[4] = {
    ITEM(user_show_page__1__item),
    ITEM(user_show_page__2__item),
    ITEM(user_show_page__3__item),
    ITEM(user_show_page__4__item)
};

/* ================================================================ 系统初始化 ================================================================ */
void Easy_Menu_Ui_Init(void)
{

    Ordinary_Page_Init(NULL, PAGE(main_page), "Main", main_page_items, 4);
        Goto_Item_Init(PAGE(main_page), ITEM(goto__start_page), "Start", PAGE(start_page));
        Goto_Item_Init(PAGE(main_page), ITEM(goto__Switch_Page), "Switch", PAGE(Switch_Page));
        Goto_Item_Init(PAGE(main_page), ITEM(goto__Data_Page), "Data", PAGE(Data_Page));
        Goto_Item_Init(PAGE(main_page), ITEM(goto__User_Show_Page), "Show", PAGE(User_Show_Page));

    Show_Page_Init(PAGE(main_page), PAGE(start_page), "Start", 150, Start_Page_Enter_Callback, Start_Page_Period_Callback, NULL);

    Ordinary_Page_Init(PAGE(main_page), PAGE(Switch_Page), "Switch", Switch_Page_items, 3);
        Switch_Item_Init(PAGE(Switch_Page), ITEM(switch_page__1__item), "LED1", &Easy_Menu_Ui_Data.LED1__data, Switch_Page__1__Item_Callback);
        Switch_Item_Init(PAGE(Switch_Page), ITEM(switch_page__2__item), "LED2", &Easy_Menu_Ui_Data.LED2__data, Switch_Page__2__Item_Callback);
        Switch_Item_Init(PAGE(Switch_Page), ITEM(switch_page__3__item), "LED3", &Easy_Menu_Ui_Data.LED3__data, Switch_Page__3__Item_Callback);

    Ordinary_Page_Init(PAGE(main_page), PAGE(Data_Page), "Data", Data_Page_items, 7);
        Data_Item_Init(PAGE(Data_Page), ITEM(data_page__1__item), "uint8_t data", UNSIGNED_CHAR, &Easy_Menu_Ui_Data.uint8_data, UNSIGNED_CHAR_VAL(1), 1, UNSIGNED_CHAR_VAL(0), 0, UNSIGNED_CHAR_VAL(0), 0, Data_Page__1__Item_Callback);
        Data_Item_Init(PAGE(Data_Page), ITEM(data_page__2__item), "uint16_t data", UNSIGNED_SHORT_INT, &Easy_Menu_Ui_Data.uint16_data, UNSIGNED_SHORT_INT_VAL(1), 1, UNSIGNED_SHORT_INT_VAL(0), 0, UNSIGNED_SHORT_INT_VAL(0), 0, Data_Page__2__Item_Callback);
        Data_Item_Init(PAGE(Data_Page), ITEM(data_page__3__item), "uint32_t data", UNSIGNED_INT, &Easy_Menu_Ui_Data.uint32_data, UNSIGNED_INT_VAL(1), 1, UNSIGNED_INT_VAL(0), 0, UNSIGNED_INT_VAL(0), 0, Data_Page__3__Item_Callback);
        Data_Item_Init(PAGE(Data_Page), ITEM(data_page__4__item), "int8_t data", SIGNED_CHAR, &Easy_Menu_Ui_Data.int8_data, SIGNED_CHAR_VAL(1), 1, SIGNED_CHAR_VAL(0), 0, SIGNED_CHAR_VAL(0), 0, Data_Page__4__Item_Callback);
        Data_Item_Init(PAGE(Data_Page), ITEM(data_page__5__item), "int16_t data", SIGNED_SHORT_INT, &Easy_Menu_Ui_Data.int16_data, SIGNED_SHORT_INT_VAL(1), 1, SIGNED_SHORT_INT_VAL(0), 0, SIGNED_SHORT_INT_VAL(0), 0, Data_Page__5__Item_Callback);
        Data_Item_Init(PAGE(Data_Page), ITEM(data_page__6__item), "int32_t data", SIGNED_INT, &Easy_Menu_Ui_Data.int32_data, SIGNED_INT_VAL(1), 1, SIGNED_INT_VAL(0), 0, SIGNED_INT_VAL(0), 0, Data_Page__6__Item_Callback);
        Data_Item_Init(PAGE(Data_Page), ITEM(data_page__7__item), "float data", FLOAT, &Easy_Menu_Ui_Data.float_data, FLOAT_VAL(0.1), 1, FLOAT_VAL(-10), 1, FLOAT_VAL(10), 1, Data_Page__7__Item_Callback);

    Ordinary_Page_Init(PAGE(main_page), PAGE(User_Show_Page), "Show", User_Show_Page_items, 4);
        Show_Item_Init(PAGE(User_Show_Page), ITEM(user_show_page__1__item), "Hour", UNSIGNED_CHAR, &Easy_Menu_Ui_Data.hours, 10, User_Show_Page__1__Item_Callback);
        Show_Item_Init(PAGE(User_Show_Page), ITEM(user_show_page__2__item), "Minute", UNSIGNED_CHAR, &Easy_Menu_Ui_Data.minutes, 10, User_Show_Page__2__Item_Callback);
        Show_Item_Init(PAGE(User_Show_Page), ITEM(user_show_page__3__item), "Second", UNSIGNED_CHAR, &Easy_Menu_Ui_Data.seconds, 10, User_Show_Page__3__Item_Callback);
        Show_Item_Init(PAGE(User_Show_Page), ITEM(user_show_page__4__item), "Millisecond", UNSIGNED_CHAR, &Easy_Menu_Ui_Data.millisecond, 10, User_Show_Page__4__Item_Callback);
    
    Easy_Menu_Goto_Page(PAGE(main_page));
}
